default_platform(:android)

platform :android do
  desc "Upload AAB to Google Play Closed Beta"
  lane :play_closed_alpha do |options|
    aab_path = ENV["ANDROID_BUILD_PATH"]

    upload_to_play_store(
      track: "alpha",
      json_key_data: ENV["GPLAY_SERVICE_JSON"],
      package_name: ENV["PLAY_PACKAGE_NAME"]
      aab: aab_path,

      # Let Play handle rollout; skip metadata & assets
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
