default_platform(:android)

def read_release_notes(options)
  if options[:notes_path]
    File.read(options[:notes_path])
  else
    options[:notes].to_s
  end
end

platform :android do
  desc "Distribute Android build to Firebase and Play"
  lane :distribute do |options|
    notes = read_release_notes(options)

    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID_ANDROID"],
      android_artifact_type: "AAB",
      android_artifact_path: ENV["ANDROID_AAB_PATH"],
      groups: "qa-testers",
      release_notes: notes
    )

    if options[:upload_to_store].to_s == "true"
      upload_to_play_store(
        track: "alpha",  # or "beta"
        json_key_data: ENV["GPLAY_SERVICE_JSON"],
        aab: ENV["ANDROID_AAB_PATH"],
        skip_upload_metadata: true,
        skip_upload_images: true,
        skip_upload_screenshots: true
      )
    end
  end
end
